version: '3'

services:
  ytdlp:
    image: jb1r/yt-dlp-image
    command: 
      - "https://www.youtube.com/c/AliMuhammadAli"
    container_name: yt-dlp-image
    
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
